// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Patrimonium.Infrastructure.Data.Context;

#nullable disable

namespace Patrimonium.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PatrimoniumDbContext))]
    [Migration("20260224213552_AddMonthlyClosingModule")]
    partial class AddMonthlyClosingModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Patrimonium.Domain.Entities.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdjustmentIndex")
                        .HasColumnType("text");

                    b.Property<int>("AdjustmentPeriodMonths")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DailyValue")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FinePercentage")
                        .HasColumnType("numeric");

                    b.Property<int>("GuaranteeType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MonthlyValue")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("PropertyId");

                    b.ToTable("contracts", (string)null);
                });

            modelBuilder.Entity("Patrimonium.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("documents", (string)null);
                });

            modelBuilder.Entity("Patrimonium.Domain.Entities.FinancialTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CompetenceMonth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("PropertyId");

                    b.ToTable("financial_transactions", (string)null);
                });

            modelBuilder.Entity("Patrimonium.Domain.Entities.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InspectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Report")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScoreCondition")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("PropertyId");

                    b.ToTable("inspections", (string)null);
                });

            modelBuilder.Entity("Patrimonium.Domain.Entities.Maintenance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CostEstimation")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("RealCost")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("ResponsiblePersonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("ResponsiblePersonId");

                    b.ToTable("maintenances", (string)null);
                });

            modelBuilder.Entity("Patrimonium.Domain.Entities.Media", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCover")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("Patrimonium.Domain.Entities.MonthlyClosing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IntegrityHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ReopenedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<int>("month")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("month");

                    b.Property<int>("year")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_monthly_closing_user");

                    b.HasIndex("UserId", "year", "month")
                        .IsUnique()
                        .HasDatabaseName("ux_monthly_closing_user_period");

                    b.ToTable("monthly_closings", (string)null);
                });

            modelBuilder.Entity("Patrimonium.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("IncomeEstimation")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Profession")
                        .HasColumnType("text");

                    b.Property<int?>("ScoreInternal")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("people", (string)null);
                });

            modelBuilder.Entity("Patrimonium.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("integer");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("integer");

                    b.Property<double>("BuiltAreaM2")
                        .HasColumnType("double precision");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Complement")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("Furnished")
                        .HasColumnType("boolean");

                    b.Property<string>("InternalName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Neighborhood")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParkingSpaces")
                        .HasColumnType("integer");

                    b.Property<int>("Purpose")
                        .HasColumnType("integer");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Suites")
                        .HasColumnType("integer");

                    b.Property<double>("TotalAreaM2")
                        .HasColumnType("double precision");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("integer");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("Patrimonium.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("EmailConfirmed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Patrimonium.Domain.Entities.Contract", b =>
                {
                    b.HasOne("Patrimonium.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Patrimonium.Domain.Entities.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Patrimonium.Domain.Entities.FinancialTransaction", b =>
                {
                    b.HasOne("Patrimonium.Domain.Entities.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Patrimonium.Domain.Entities.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Patrimonium.Domain.Entities.Inspection", b =>
                {
                    b.HasOne("Patrimonium.Domain.Entities.Contract", null)
                        .WithMany()
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Patrimonium.Domain.Entities.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Patrimonium.Domain.Entities.Maintenance", b =>
                {
                    b.HasOne("Patrimonium.Domain.Entities.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Patrimonium.Domain.Entities.Person", null)
                        .WithMany()
                        .HasForeignKey("ResponsiblePersonId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Patrimonium.Domain.Entities.Media", b =>
                {
                    b.HasOne("Patrimonium.Domain.Entities.Property", null)
                        .WithMany()
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Patrimonium.Domain.Entities.MonthlyClosing", b =>
                {
                    b.OwnsOne("Patrimonium.Domain.Entities.Snapshot.MonthlySnapshot", "Snapshot", b1 =>
                        {
                            b1.Property<Guid>("MonthlyClosingId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.HasKey("MonthlyClosingId");

                            b1.ToTable("monthly_closings");

                            b1.WithOwner()
                                .HasForeignKey("MonthlyClosingId");

                            b1.OwnsOne("Patrimonium.Domain.Entities.Snapshot.FinancialSnapshot", "Financial", b2 =>
                                {
                                    b2.Property<Guid>("MonthlySnapshotMonthlyClosingId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("CashFlow")
                                        .HasColumnType("numeric")
                                        .HasColumnName("financial_cash_flow");

                                    b2.Property<decimal>("NetResult")
                                        .HasColumnType("numeric")
                                        .HasColumnName("financial_net_result");

                                    b2.Property<decimal>("TotalExpense")
                                        .HasColumnType("numeric")
                                        .HasColumnName("financial_total_expense");

                                    b2.Property<decimal>("TotalIncome")
                                        .HasColumnType("numeric")
                                        .HasColumnName("financial_total_income");

                                    b2.Property<decimal>("TotalMaintenance")
                                        .HasColumnType("numeric")
                                        .HasColumnName("financial_total_maintenance");

                                    b2.Property<decimal>("TotalTax")
                                        .HasColumnType("numeric")
                                        .HasColumnName("financial_total_tax");

                                    b2.HasKey("MonthlySnapshotMonthlyClosingId");

                                    b2.ToTable("monthly_closings");

                                    b2.WithOwner()
                                        .HasForeignKey("MonthlySnapshotMonthlyClosingId");
                                });

                            b1.OwnsOne("Patrimonium.Domain.Entities.Snapshot.OperationalSnapshot", "Operational", b2 =>
                                {
                                    b2.Property<Guid>("MonthlySnapshotMonthlyClosingId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("ActiveContracts")
                                        .HasColumnType("integer")
                                        .HasColumnName("op_active_contracts");

                                    b2.Property<int>("ActiveProperties")
                                        .HasColumnType("integer")
                                        .HasColumnName("op_active_properties");

                                    b2.Property<decimal>("OccupancyRate")
                                        .HasColumnType("numeric")
                                        .HasColumnName("op_occupancy_rate");

                                    b2.Property<int>("OpenMaintenances")
                                        .HasColumnType("integer")
                                        .HasColumnName("op_open_maintenances");

                                    b2.Property<decimal>("VacancyRate")
                                        .HasColumnType("numeric")
                                        .HasColumnName("op_vacancy_rate");

                                    b2.Property<int>("VacantProperties")
                                        .HasColumnType("integer")
                                        .HasColumnName("op_vacant_properties");

                                    b2.HasKey("MonthlySnapshotMonthlyClosingId");

                                    b2.ToTable("monthly_closings");

                                    b2.WithOwner()
                                        .HasForeignKey("MonthlySnapshotMonthlyClosingId");
                                });

                            b1.OwnsOne("Patrimonium.Domain.Entities.Snapshot.PatrimonialSnapshot", "Patrimonial", b2 =>
                                {
                                    b2.Property<Guid>("MonthlySnapshotMonthlyClosingId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Appreciation")
                                        .HasColumnType("numeric")
                                        .HasColumnName("pat_appreciation");

                                    b2.Property<decimal>("RoiAccumulated")
                                        .HasColumnType("numeric")
                                        .HasColumnName("pat_roi_accumulated");

                                    b2.Property<decimal>("TotalEstimatedValue")
                                        .HasColumnType("numeric")
                                        .HasColumnName("pat_total_estimated_value");

                                    b2.Property<decimal>("TotalInvested")
                                        .HasColumnType("numeric")
                                        .HasColumnName("pat_total_invested");

                                    b2.HasKey("MonthlySnapshotMonthlyClosingId");

                                    b2.ToTable("monthly_closings");

                                    b2.WithOwner()
                                        .HasForeignKey("MonthlySnapshotMonthlyClosingId");
                                });

                            b1.OwnsMany("Patrimonium.Domain.Entities.Snapshot.PropertySnapshot", "Properties", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Expense")
                                        .HasColumnType("numeric")
                                        .HasColumnName("property_expense");

                                    b2.Property<decimal>("Income")
                                        .HasColumnType("numeric")
                                        .HasColumnName("property_income");

                                    b2.Property<string>("InternalName")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("property_internal_name");

                                    b2.Property<decimal>("NetResult")
                                        .HasColumnType("numeric")
                                        .HasColumnName("property_net_result");

                                    b2.Property<Guid>("PropertyId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("property_id");

                                    b2.Property<string>("Purpose")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("property_purpose");

                                    b2.Property<string>("Type")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("property_type");

                                    b2.Property<Guid>("monthly_closing_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("monthly_closing_id");

                                    b2.ToTable("monthly_snapshot_properties", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("monthly_closing_id");
                                });

                            b1.OwnsMany("Patrimonium.Domain.Entities.Snapshot.TransactionSnapshot", "Transactions", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric")
                                        .HasColumnName("amount");

                                    b2.Property<int>("Category")
                                        .HasColumnType("integer")
                                        .HasColumnName("category");

                                    b2.Property<DateTime>("Date")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("date");

                                    b2.Property<Guid>("TransactionId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("transaction_id");

                                    b2.Property<int>("Type")
                                        .HasColumnType("integer")
                                        .HasColumnName("type");

                                    b2.Property<Guid>("monthly_closing_id")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("monthly_closing_id");

                                    b2.ToTable("monthly_snapshot_transactions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("monthly_closing_id");
                                });

                            b1.Navigation("Financial")
                                .IsRequired();

                            b1.Navigation("Operational")
                                .IsRequired();

                            b1.Navigation("Patrimonial")
                                .IsRequired();

                            b1.Navigation("Properties");

                            b1.Navigation("Transactions");
                        });

                    b.OwnsOne("Patrimonium.Domain.ValueObjects.ClosingPeriod", "Period", b1 =>
                        {
                            b1.Property<Guid>("MonthlyClosingId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Month")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("integer")
                                .HasColumnName("month");

                            b1.Property<int>("Year")
                                .ValueGeneratedOnUpdateSometimes()
                                .HasColumnType("integer")
                                .HasColumnName("year");

                            b1.HasKey("MonthlyClosingId");

                            b1.ToTable("monthly_closings");

                            b1.WithOwner()
                                .HasForeignKey("MonthlyClosingId");
                        });

                    b.Navigation("Period")
                        .IsRequired();

                    b.Navigation("Snapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("Patrimonium.Domain.Entities.Property", b =>
                {
                    b.OwnsOne("Patrimonium.Domain.ValueObjects.PropertyValuation", "Valuation", b1 =>
                        {
                            b1.Property<Guid>("PropertyId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("EstimatedValue")
                                .HasColumnType("numeric")
                                .HasColumnName("estimated_value");

                            b1.Property<decimal>("InvestedValue")
                                .HasColumnType("numeric")
                                .HasColumnName("invested_value");

                            b1.HasKey("PropertyId");

                            b1.ToTable("properties");

                            b1.WithOwner()
                                .HasForeignKey("PropertyId");
                        });

                    b.Navigation("Valuation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
